### ISSUE TITLE
Shortcut to move card to front of new card queue (feature request)

### ISSUE THREAD

**Issue by hanseinotabi** [simgunz/anki-addons_fast-cards-reposition#3]
Just wondering if it would be possible to add a keyboard shortcut to reposition a card from the browser at the front of the new card queue.

When I come across new vocab words in real life, I want to bring a card with that word on it to the front of my deck (10k+ cards), so I can review it next. Sometimes I do this with 10~20 cards per session, and it's tedious to do it from the menu Edit>Reposition>OK. So it'd be great to just highlight a card and use a shortcut to reposition it at '0'.

If it's easy enough, I'd really appreciate it! If not, no worries.

**Comment by hanseinotabi** [comment]
I've been traveling, so I didn't get a chance to check this out until now. Thanks so much for adding this!

**Comment by simgunz** [comment]
Glad you liked it.
